import './style.css';

type Mode='spatial'|'equipment'|'body'; type Loadout='light'|'heavy'; type Condition='backpack-only'|'body-slots'; type Location='back'|'chest'|'waist';
type Item={rotated:boolean;id:number;name:string;w:number;h:number;value:number;visual:string;tint:string;edge:string;x?:number;y?:number;locked?:boolean;asset?:string;bodyLocation?:Location;onBody?:Location};
type Spec=[string,number,number,number,string,string,string,Location?];
const spatial:Spec[]=[['急救药',1,1,15,'medicine','#e4eddf','#749071'],['罐装肉',1,2,25,'can','#eedcc6','#af8b60'],['维修工具',2,2,50,'tool','#d6e2dc','#6e9081'],['绷带',2,1,20,'bandage','#f0e9cf','#ae9c68'],['废旧电池',2,2,35,'battery','#d9e2ce','#879663'],['干燥种子',2,2,30,'seed','#e2e6be','#8e9a55'],['机械零件',2,3,65,'gear','#dae1e7','#7a8e9e'],['未知组织',2,3,80,'organ','#e7d1db','#a56e8c'],['旧式步枪',1,4,70,'rifle','#dfd8c9','#8f8066'],['黑色遗物',3,3,120,'relic','#d6d1e3','#817395'],['木板',1,3,18,'plank','#eadbc1','#aa8855'],['密封仪器',3,5,190,'device','#cddfdc','#648f85']];
const equipmentLoot:Spec[]=[['罐装肉',1,2,25,'can','#eedcc6','#af8b60'],['废旧电池',2,2,35,'battery','#d9e2ce','#879663'],['机械零件',2,3,65,'gear','#dae1e7','#7a8e9e'],['未知组织',2,3,80,'organ','#e7d1db','#a56e8c'],['黑色遗物',3,3,120,'relic','#d6d1e3','#817395'],['木板',1,3,18,'plank','#eadbc1','#aa8855'],['密封仪器',3,5,190,'device','#cddfdc','#648f85']];
const bodySpecs:Spec[]=[['Compact Sidearm',1,2,30,'sidearm','#d9e1dc','#687b70','waist'],['Canned Food',1,2,20,'can','#eedcc6','#af8b60'],['Field Medkit',2,3,45,'medicine','#e4eddf','#749071','chest'],['Mechanical Parts',3,4,65,'gear','#dae1e7','#7a8e9e'],['Old Rifle',1,5,75,'rifle','#dfd8c9','#8f8066','back'],['Ammo Pouch',2,3,40,'battery','#d9e2ce','#879663','waist'],['Utility Pouch',2,2,35,'tool','#d6e2dc','#6e9081','chest'],['Field Tool',2,4,55,'plank','#eadbc1','#aa8855','back'],['Sealed Instrument',5,5,180,'device','#cddfdc','#648f85']];
const assets={sidearm:new URL('./assets/equipment_sidearm.svg?no-inline',import.meta.url).href,medkit:new URL('./assets/equipment_field_medkit.svg?no-inline',import.meta.url).href,rifle:new URL('./assets/equipment_old_rifle.svg?no-inline',import.meta.url).href,armor:new URL('./assets/equipment_field_armor.svg?no-inline',import.meta.url).href};
const equipmentFor=(l:Loadout):Item[]=>(l==='light'?[{id:-1,name:'Compact Sidearm',w:1,h:2,x:0,y:0,asset:assets.sidearm},{id:-2,name:'Field Medkit',w:1,h:1,x:1,y:0,asset:assets.medkit}]:[{id:-3,name:'Old Rifle',w:1,h:4,x:0,y:0,asset:assets.rifle},{id:-4,name:'Field Armor',w:2,h:3,x:1,y:0,asset:assets.armor},{id:-5,name:'Field Medkit',w:1,h:1,x:3,y:0,asset:assets.medkit}]).map(i=>({...i,rotated:false,value:0,visual:'',tint:'#d8d5c8',edge:'#6e6a5d',locked:true}));
const drawings:Record<string,string>={
 medicine:'<rect x="20" y="14" width="24" height="42" rx="7" fill="#eef5de"/><path d="M24 8h16v10H24z" fill="#59735c"/><path d="M29 27h6v7h7v6h-7v7h-6v-7h-7v-6h7z" fill="#cc5f50"/>',
 can:'<rect x="15" y="12" width="34" height="44" rx="7" fill="#bb6b4b"/><ellipse cx="32" cy="13" rx="17" ry="6" fill="#ddd6bd"/><path d="M17 26h30v17H17z" fill="#ecd6a4"/><path d="M25 32q10-9 15 4q-10 8-15-4" fill="#ad664c"/>',
 tool:'<path d="M24 19v-7h16v7" fill="none" stroke="#53675c" stroke-width="5"/><rect x="8" y="21" width="48" height="32" rx="5" fill="#668e79"/><path d="M9 33h46M30 29v10" stroke="#e5dec0" stroke-width="5"/>',
 bandage:'<rect x="7" y="23" width="50" height="21" rx="10" fill="#d3bb88" transform="rotate(-25 32 32)"/><path d="M24 22h17v22H24z" fill="#f6ead2" transform="rotate(-25 32 32)"/>',
 battery:'<rect x="12" y="19" width="40" height="36" rx="4" fill="#697d59"/><path d="M17 12h9v7h-9zm21 0h9v7h-9z" fill="#a68f61"/><path d="m35 23-12 16h10l-4 12 15-19H33z" fill="#ead799"/>',
 seed:'<path d="m17 12 30 0-4 10 9 31H12l9-31z" fill="#b8a371"/><path d="M22 19h21" stroke="#655f3c" stroke-width="3"/><path d="M32 48V29q-14-7-14 4q0 9 14 7q15-1 14-11q-9-3-14 7" fill="#627c42"/>',
 gear:'<path d="M26 7h12l2 9 8-4 8 9-6 7 7 6-4 12-10-1-2 11H26l-3-10-10 3-7-11 7-8-5-8 10-9 8 4z" fill="#8596a1"/><circle cx="32" cy="32" r="11" fill="#dfe8e9"/><circle cx="32" cy="32" r="5" fill="#647780"/>',
 organ:'<path d="M32 13c-16-14-30 12-17 29s31 18 36-1S42 4 32 13" fill="#ac6e86"/><path d="M31 13q12 14-3 30m-12-18q14-7 20 7m-7 9 12 6" fill="none" stroke="#e2afba" stroke-width="3"/>',
 rifle:'<path d="m28 4 7 0v27h7v7h-9l-2 22H20l5-28z" fill="#57625c"/><path d="m24 39 10 0-3 22H18z" fill="#94704e"/><path d="M25 23h11v12H25z" fill="#a18259"/>',
 sidearm:'<path d="M10 18h38v18H31l-4 22H16l5-22H10z" fill="#586963"/><path d="M40 22h15v8H40z" fill="#9c8059"/>',
 relic:'<path d="m32 5 20 17-6 30-28 0-7-30z" fill="#514b62"/><path d="m32 14 12 20-12 12-12-12z" fill="#92819f"/><ellipse cx="32" cy="32" rx="10" ry="5" fill="#dac398"/><circle cx="32" cy="32" r="3" fill="#40374e"/>',
 plank:'<path d="m22 4 20 4-4 52-20-3z" fill="#b58e57"/><path d="M29 8l-5 44m12-37-5 35" stroke="#866238" stroke-width="2"/>',
 device:'<rect x="12" y="6" width="40" height="54" rx="6" fill="#59877e"/><rect x="18" y="13" width="28" height="20" rx="3" fill="#d1e4c5"/><path d="m21 25 6-5 6 6 10-8" stroke="#59877e" fill="none" stroke-width="3"/><circle cx="24" cy="45" r="5" fill="#d7c393"/><circle cx="40" cy="45" r="5" fill="#a7c5b4"/>',
};
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T,board=$('board'),tray=$('tray'),drop=$('drop');
const bodyPanel=$<HTMLElement>('body-panel');
const slots=[...bodyPanel.querySelectorAll<HTMLElement>('[data-body-slot]')];let mode:Mode='body',loadout:Loadout='light',condition:Condition='body-slots',items:Item[]=[],bodyItems:Item[]=[],equipment:Item[]=[],discarded:Item[]=[],index=0,current:Item|null=null;
let drag:{item:Item;w:number;h:number;rotated:boolean;ox:number;oy:number;px:number;py:number;ghost:HTMLElement;original:HTMLElement;pointer:number}|null=null;const preview=document.createElement('div');preview.className='placement';
const cell=()=>board.clientWidth/6,specs=()=>mode==='spatial'?spatial:mode==='equipment'?equipmentLoot:bodySpecs,loc=(l:Location)=>({back:'Back',chest:'Chest',waist:'Waist'}[l]);
const describe=(i:Item)=>i.locked?`${i.name} · ${i.w} × ${i.h} · Locked Equipment`:`${i.name} · ${i.w} × ${i.h} · 价值 ${i.value}${i.bodyLocation?` · ${loc(i.bodyLocation)}`:''}`;
function art(i:Item){return i.locked?`<div class="item-art"><img src="${i.asset}" alt=""></div><span class="lock">LOCKED</span>`:`<div class="item-art"><svg viewBox="0 0 64 64" aria-hidden="true">${drawings[i.visual]}</svg></div><span class="price">${i.value}</span>`}
function element(i:Item,inTray=false,onBody=false){const el=document.createElement('div');el.className=`item${inTray?' in-tray':''}${onBody?' on-body':''}${i.locked?' equipment':''}`;el.dataset.id=String(i.id);el.title=describe(i);el.setAttribute('aria-label',describe(i));el.style.setProperty('--tint',i.tint);el.style.setProperty('--edge',i.edge);el.style.width=`${i.w*cell()}px`;el.style.height=`${i.h*cell()}px`;el.innerHTML=art(i);el.style.setProperty('--art-size',`${Math.min(105,Math.min(i.w,i.h)*cell()-12)}px`);el.style.setProperty('--art-angle',!onBody&&i.rotated?'90deg':'0deg');if(!inTray&&!onBody){el.style.left=`${i.x!*cell()}px`;el.style.top=`${i.y!*cell()}px`}el.addEventListener('pointerenter',()=>{$('details').textContent=describe(i)});if(!i.locked)el.addEventListener('pointerdown',e=>start(e,i,el));return el}
function render(){board.replaceChildren(...equipment.map(i=>element(i)),...items.map(i=>element(i)));slots.forEach(s=>{s.querySelector('.item')?.remove();const slot=s.dataset.bodySlot?.toLowerCase();const i=bodyItems.find(v=>v.onBody===slot);if(i)s.append(element(i,false,true))});tray.replaceChildren();const all=specs();if(current)tray.append(element(current,true));else tray.textContent=index===all.length?'全部物品已处理':'已处理，点击下一件';$('next').toggleAttribute('disabled',!!current||index===all.length);$('progress').textContent=`${index} / ${all.length}`;const kept=[...items,...bodyItems],value=kept.reduce((n,i)=>n+i.value,0),area=items.reduce((n,i)=>n+i.w*i.h,0),ea=equipment.reduce((n,i)=>n+i.w*i.h,0);$('value').textContent=`价值 ${value}`;$('stats').textContent=mode==='equipment'?`Equipment ${ea} / 48 · Loot ${area} cells · 总占格 ${ea+area} / 48`:mode==='body'?`背包占格 ${area} / 48 · 身体携带 ${bodyItems.length} / 3 · 保留 ${kept.length} 件`:`占格 ${area} / 48 · 保留 ${items.length} 件`;$('loadout-label').textContent=loadout==='light'?'Light Loadout · Equipment 3 / 48':'Heavy Loadout · Equipment 11 / 48';$('discarded').replaceChildren(...discarded.map(i=>{const li=document.createElement('li');li.textContent=describe(i);return li}));const done=index===all.length&&!current;$('summary').hidden=!done;if(mode==='equipment')$('summary-text').textContent=`Loadout：${loadout==='light'?'Light':'Heavy'}。Equipment Area：${ea}。Loot Kept：${items.map(i=>i.name).join('、')||'无'}。Loot Value Kept：${value}。Loot Discarded：${discarded.map(i=>i.name).join('、')||'无'}。`;else if(mode==='body')$('summary-text').textContent=`Test Condition：${condition==='body-slots'?'Body Slots Available':'Backpack Only'}。Backpack：${items.map(i=>i.name).join('、')||'无'}。Body：${bodyItems.map(i=>`${loc(i.onBody!)}—${i.name}`).join('、')||'无'}。Discarded：${discarded.map(i=>i.name).join('、')||'无'}。Total Kept Value：${value}。`;else $('summary-text').textContent=`保留：${items.map(i=>i.name).join('、')||'无'}。总价值：${value}。丢弃：${discarded.map(i=>i.name).join('、')||'无'}。`}
function next(){const a=specs();if(current||index>=a.length)return;const[name,w,h,value,visual,tint,edge,bodyLocation]=a[index];current={rotated:false,id:index++,name,w,h,value,visual,tint,edge,bodyLocation};$('details').textContent=describe(current);render()}
function legal(x:number,y:number,w:number,h:number,id:number){return x>=0&&y>=0&&x+w<=6&&y+h<=8&&![...equipment,...items].some(i=>i.id!==id&&x<i.x!+i.w&&x+w>i.x!&&y<i.y!+i.h&&y+h>i.y!)}
function target(){const r=board.getBoundingClientRect();return{x:Math.round((drag!.px-drag!.ox-r.left)/cell()),y:Math.round((drag!.py-drag!.oy-r.top)/cell())}}function over(el:HTMLElement){const r=el.getBoundingClientRect();return drag!.px>=r.left&&drag!.px<=r.right&&drag!.py>=r.top&&drag!.py<=r.bottom}const hoveredSlot=()=>slots.find(over);const slotLocation=(s:HTMLElement)=>s.dataset.bodySlot!.toLowerCase() as Location;function bodyLegal(s:HTMLElement,i:Item){const location=slotLocation(s);return mode==='body'&&condition==='body-slots'&&i.bodyLocation===location&&!bodyItems.some(v=>v.id!==i.id&&v.onBody===location)}
function show(){if(!drag)return;const d=drag;d.ghost.style.width=`${d.w*cell()}px`;d.ghost.style.height=`${d.h*cell()}px`;d.ghost.style.left=`${d.px-d.ox}px`;d.ghost.style.top=`${d.py-d.oy}px`;d.ghost.style.setProperty('--art-angle',d.rotated?'90deg':'0deg');drop.classList.toggle('active',over(drop));preview.remove();slots.forEach(s=>s.classList.remove('active','invalid'));const s=hoveredSlot();if(s)s.classList.add(bodyLegal(s,d.item)?'active':'invalid');if(over(board)){const{x,y}=target();preview.style.cssText=`left:${x*cell()}px;top:${y*cell()}px;width:${d.w*cell()}px;height:${d.h*cell()}px`;preview.className=`placement${legal(x,y,d.w,d.h,d.item.id)?'':' invalid'}`;board.append(preview)}}
function start(e:PointerEvent,item:Item,el:HTMLElement){if(e.button!==0||drag||item.locked)return;e.preventDefault();const r=el.getBoundingClientRect(),ghost=el.cloneNode(true)as HTMLElement,rx=(e.clientX-r.left)/r.width,ry=(e.clientY-r.top)/r.height;ghost.className='item dragging';document.body.append(ghost);drag={item,w:item.w,h:item.h,rotated:item.rotated,ox:rx*item.w*cell(),oy:ry*item.h*cell(),px:e.clientX,py:e.clientY,ghost,original:el,pointer:e.pointerId};el.style.opacity='.25';el.setPointerCapture(e.pointerId);$('details').textContent=describe(item);show()}
function cancel(message='已取消，物品回到原处。'){if(!drag)return;drag.ghost.remove();drag.original.style.opacity='';$('details').textContent=describe(drag.item);drag=null;preview.remove();drop.classList.remove('active');slots.forEach(s=>s.classList.remove('active','invalid'));$('message').textContent=message;render()}
window.addEventListener('pointermove',e=>{if(drag&&e.pointerId===drag.pointer){drag.px=e.clientX;drag.py=e.clientY;show()}});window.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.pointer)return;drag.px=e.clientX;drag.py=e.clientY;const d=drag,{x,y}=target(),s=hoveredSlot();let msg='这里放不下，物品已回到原处。';if(over(drop)){items=items.filter(i=>i.id!==d.item.id);bodyItems=bodyItems.filter(i=>i.id!==d.item.id);discarded.push(d.item);if(current===d.item)current=null;msg=`已丢弃 ${d.item.name}。`}else if(s&&bodyLegal(s,d.item)){items=items.filter(i=>i.id!==d.item.id);d.item.onBody=slotLocation(s);delete d.item.x;delete d.item.y;bodyItems=bodyItems.filter(i=>i.id!==d.item.id);bodyItems.push(d.item);if(current===d.item)current=null;msg=`已将 ${d.item.name} 放到 ${loc(d.item.onBody)}。`}else if(over(board)&&legal(x,y,d.w,d.h,d.item.id)){bodyItems=bodyItems.filter(i=>i.id!==d.item.id);delete d.item.onBody;Object.assign(d.item,{x,y,w:d.w,h:d.h,rotated:d.rotated});if(!items.some(i=>i.id===d.item.id))items.push(d.item);if(current===d.item)current=null;msg=`已放好 ${d.item.name}。`}cancel(msg)});window.addEventListener('pointercancel',()=>cancel());window.addEventListener('blur',()=>cancel());
window.addEventListener('keydown',e=>{if(!drag)return;if(e.key.toLowerCase()==='r'&&!e.repeat){e.preventDefault();const d=drag,nx=d.ox/(d.w*cell()),ny=d.oy/(d.h*cell());[d.w,d.h]=[d.h,d.w];d.rotated=!d.rotated;d.ox=(d.rotated?1-ny:ny)*d.w*cell();d.oy=(d.rotated?nx:1-nx)*d.h*cell();$('details').textContent=`${describe(d.item)} · 当前方向 ${d.w} × ${d.h}`;show()}else if(e.key==='Escape')cancel()});window.addEventListener('resize',()=>drag?cancel():render());
function reset(msg:string){if(drag)cancel();items=[];bodyItems=[];discarded=[];index=0;current=null;equipment=mode==='equipment'?equipmentFor(loadout):[];next();$('message').textContent=msg}
function selectMode(m:Mode){mode=m;$('loadout-controls').hidden=mode!=='equipment';$('condition-controls').hidden=mode!=='body';bodyPanel.hidden=mode!=='body'||condition==='backpack-only';$('experiment').textContent=mode==='equipment'?'EXP-003 · TESTING':mode==='body'?'EXP-048 · TESTING':'EXP-001 · MAYBE';$('subtitle').textContent=mode==='equipment'?'相同战利品，不同出门装备占格。':mode==='body'?'相同物品，比较仅背包与身体携带位置。':'拖入背包，转个方向，决定带走什么。';$('equipment-note').hidden=mode!=='equipment';$('body-note').hidden=mode!=='body';$('controls-text').innerHTML=mode==='body'?'拖拽至背包或匹配身体位置 · <kbd>R</kbd> 旋转背包方向 · <kbd>Esc</kbd> 取消':mode==='equipment'?'拖拽移动 · <kbd>R</kbd> 旋转手中 Loot · <kbd>Esc</kbd> 取消':'拖拽移动 · <kbd>R</kbd> 旋转手中物品 · <kbd>Esc</kbd> 取消';document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.classList.toggle('selected',b.dataset.mode===mode));reset('已切换 Experiment Mode，并开始全新 Session。')}
function selectLoadout(l:Loadout){loadout=l;document.querySelectorAll<HTMLButtonElement>('[data-loadout]').forEach(b=>b.classList.toggle('selected',b.dataset.loadout===loadout));reset(`已切换为 ${loadout==='light'?'Light':'Heavy'} Loadout，并开始全新 Session。`)}function selectCondition(c:Condition){condition=c;bodyPanel.hidden=condition==='backpack-only';$('condition-label').textContent=condition==='body-slots'?'Body Slots Available':'Backpack Only';document.querySelectorAll<HTMLButtonElement>('[data-condition]').forEach(b=>b.classList.toggle('selected',b.dataset.condition===condition));reset(`已切换为 ${condition==='body-slots'?'Body Slots Available':'Backpack Only'}，并开始全新 Session。`)}
$('next').addEventListener('click',next);$('restart').addEventListener('click',()=>reset('已重开当前 Mode 的相同固定序列。'));document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.addEventListener('click',()=>selectMode(b.dataset.mode as Mode)));document.querySelectorAll<HTMLButtonElement>('[data-loadout]').forEach(b=>b.addEventListener('click',()=>selectLoadout(b.dataset.loadout as Loadout)));document.querySelectorAll<HTMLButtonElement>('[data-condition]').forEach(b=>b.addEventListener('click',()=>selectCondition(b.dataset.condition as Condition)));selectCondition('body-slots');selectMode('body');
